version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
    - 4.1.3
  - dependency-name: com.mikepenz:fastadapter
    versions:
    - 5.4.0
  - dependency-name: androidx.recyclerview:recyclerview
    versions:
    - 1.2.0-rc01
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: androidx.core:core-ktx
    versions:
    - 1.5.0-beta02
